### ISSUE TITLE
Breaks switching of skins

### ISSUE THREAD

**Issue by arp242** [tinymighty/skinny#4]
Including this extension breaks user-configured switching of skins. It will always show `$wgDefaultskin`.

Using MediaWiki 1.26.2.

**Comment by andru** [comment]
Hm. I'm guessing this has to do with the `setskin` parser function code,
which has to manually override the skin to work; it's probably doing so
regardless of whether it's being used or not.  I'll look into it when I
can, and I'll gladly receive a pull request if you fix it meanwhile.
